The problem stems from the fact that the parameters steps_per_epoch and 
        validation_steps need to be equal to the total number of data points divided by the batch_size.
        
Change the model.fit() function to:
history_of_model = model.fit_generator(training_set,
                              steps_per_epoch = int(numberF_trainingData/batch_size),
                              epochs = 25,
                              validation_data = test_set,
                              validation_steps = int(numberF_validationData/batch_size)
                              )
